### ISSUE TITLE
FEAT: Allow output in JSON

### ISSUE THREAD

**Issue by pllim** [scikit-hep/repo-review#41]
Either from CLI (e.g., `-o myfilename.json`) or from programmatic API. I would probably use the latter.

Goal 1: Allow looping through multiple repositories and collecting the results in a single JSON file.

Goal 2: Allow injecting checks from other tools (e.g., last commit date and so on from separate [PyGithub](https://github.com/PyGithub/PyGithub) calls) into the same JSON for further processing.

cc @lwasser

**Comment by lwasser** [comment]
💯 output to something json / json like would be a very useful feature!
