### ISSUE TITLE
FEAT: Clearer icon for skipped status

### ISSUE THREAD

**Issue by pllim** [scikit-hep/repo-review#42]
During demo at Scientific Python Developers Summit 2023, some people expressed desire to replace the orange "skipped" icon with a gray one, so one can easily distinguish it from "failed" status.

Another idea is to use emojis, example:

👍 
🤔 
😱

**Comment by henryiii** [comment]
Touched up formatting and icons a bit, live at https://scikit-hep.github.io/repo-review (URL likely changing soon).
